apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - namespace.yaml
  
namespace: cna-covid-data-staging

commonLabels:
  app: cna-covid-data

images:
  - name: harbor.dev.pkhamdee.com/cna-covid/covid-data
    newName: harbor.dev.pkhamdee.com/cna-covid/covid-data@sha256:114793b4dba8a2c7334b079755d57835ef753e1e419b2fab42ae731a71fca010

patchesStrategicMerge:
  - custom-ingress.yaml
