apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - namespace.yaml
  
namespace: cna-covid-data-staging

commonLabels:
  app: cna-covid-data

images:
  - name: harbor.dev.pkhamdee.com/cna-covid/covid-data
    newTag: latest 

patchesStrategicMerge:
  - custom-ingress.yaml
