apiVersion: v1
kind: Service
metadata:
  labels:
    app: cna-covid-data
  name: cna-covid-data
spec:
  ports:
    - port: 80
      name: cna-covid-data
      protocol: TCP
      targetPort: 8080
  selector:
    app: cna-covid-data
  type: ClusterIP
  ---
  apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    namespace: monitoring
    name: cna-covid-data
    labels:
      release: monitoring-release
  spec:
    selector:
      matchLabels:
        app: cna-covid-data
    namespaceSelector:
      matchNames:
        - default
    endpoints:
      - port: cna-covid-data
        path: '/actuator/prometheus'
        interval: 1s